repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0   # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
    args: [--maxkb=500]
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml
  - id: mixed-line-ending
  - id: check-symlinks
  - id: end-of-file-fixer
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.7
  hooks:
    # Run the linter.
  - id: ruff
    args: [--fix]
    # Run the formatter.
  - id: ruff-format
