name: CI and release

on: [push, pull_request]

concurrency:
  group: ${{ github.event.number || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Debug
      run: |
        find . -iname "*.whl"
        find . -iname "*.tar.gz"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

#     - name: Upload tar.gz and whl
#       uses: actions/upload-artifact@v3
#       with:
#         name: deliverables
#         path: |
#           ./sphinx_rfc2119-*.tar.gz
#           sphinx_rfc2119-*-py3-none-any.whl

  publish:
    runs-on: ubuntu-latest
    needs: [test, pre-commit]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: download release artefact
      uses: actions/download-artifact@master
      with:
        name: dist

    - name: Debug
      run: |
        find . -iname "*.whl"
        find . -iname "*.tar.gz"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          sphinx_rfc2119-*.tar.gz
          sphinx_rfc2119-*-py3-none-any.whl
